name: React Native Build and Release

on:
  push:
    branches:
      - produccion

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: |
        npm install

    - name: Setup Android SDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Configure SDK
      run: echo "y" | $RUNNER_TOOL_CACHE/adopt-$(java -version 2>&1 | awk -F '"' '/version/ {print $2}')-hotspot-x64/bin/sdkmanager "platforms;android-30"

    - name: Build Android Release
      run: |
        cd android && ./gradlew assembleRelease
