name: React Native Build and Release

on:
  push:
    branches:
      - produccion

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Dependencies
      run: |
        npm install

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Make gradlew executable
      run: cd android && chmod +x ./gradlew
       
    - name: Build Android Release
      run: |
        cd android && ./gradlew assembleDebug
    
    - name: Check files
      run: |
        cd android/app/build/outputs/apk/debug && ls -l

    - name: Upload
      uses: nickwph/firebase-app-distribution-action@v1
      with:
        file: android/app/build/outputs/apk/debug/app-debug.apk
        app: ${{ secrets.FIREBASE_APP_ID }}
        credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
        credentials-file: ${{ secrets.FIREBASE_CREDENTIALS_FILE }}  # Optional: This is ignored if credentials is defined.
        release-notes: ""                    # Optional
        release-notes-file: ""               # Optional
        testers: ""                          # Optional
        testers-file: ""                     # Optional
        groups: ""                           # Optional
        groups-file: ""                      # Optional
        debug: false                         # Optional: Default false. A flag you can include to print verbose log output.
        cache: true                          # Optional: Default true. Whether to cache the firebase tools for next job, keeping this "true" will speed up the build.
        upgrade: true                        # Optional: Default true. Whether to attempt to upgrade firebase tools when cache is "true", turning this "false" will speed up the build.
        token: ${{ secrets.FIREBASE_TOKEN }} # Deprecated

    # - name: Upload Artifact to Firebase App Distribution
    #   uses: wzieba/Firebase-Distribution-Github-Action@v1
    #   with:
    #     appId: ${{ secrets.FIREBASE_APP_ID }}
    #     serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
    #     groups: testers
    #     file: android/app/build/outputs/apk/debug/app-debug.apk
    #     releaseNotes: ${{ inputs.release_notes }}


    # - name: Install Firebase CLI
    #   run: |
    #     npm install -g firebase-tools
    
    # - name: Upload to Firebase App Distribution
    #   run: |
    #     firebase appdistribution:distribute app-debug.apk --app ${{ secrets.FIREBASE_APP_ID }} --token ${{ secrets.FIREBASE_TOKEN }} --groups testers --release-notes "$GITHUB_REF: ${{ github.event.head_commit.message }}"
    #   working-directory: android/app/build/outputs/apk/debug/
    #   env:
    #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}